"""empty message

Revision ID: af332d0d5507
Revises: d063b96f8c5b
Create Date: 2021-05-24 19:43:05.934517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af332d0d5507'
down_revision = 'd063b96f8c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('executable_path', sa.String(), nullable=True),
    sa.Column('system_configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('plugin_configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('videos', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processed')
    op.drop_table('plugins')
    # ### end Alembic commands ###
